#!/bin/bash
# Downloads all 78 Rider-Waite cards from Wikimedia Commons

mkdir -p public/cards
BASE="https://upload.wikimedia.org/wikipedia/commons"

echo "Downloading Major Arcana..."
curl -L "$BASE/9/90/RWS_Tarot_00_Fool.jpg" -o public/cards/major-00.jpg && echo "  00 Fool ✓"
curl -L "$BASE/d/de/RWS_Tarot_01_Magician.jpg" -o public/cards/major-01.jpg && echo "  01 Magician ✓"
curl -L "$BASE/8/88/RWS_Tarot_02_High_Priestess.jpg" -o public/cards/major-02.jpg && echo "  02 High Priestess ✓"
curl -L "$BASE/d/d2/RWS_Tarot_03_Empress.jpg" -o public/cards/major-03.jpg && echo "  03 Empress ✓"
curl -L "$BASE/c/c3/RWS_Tarot_04_Emperor.jpg" -o public/cards/major-04.jpg && echo "  04 Emperor ✓"
curl -L "$BASE/8/8d/RWS_Tarot_05_Hierophant.jpg" -o public/cards/major-05.jpg && echo "  05 Hierophant ✓"
curl -L "$BASE/3/3a/TheLovers.jpg" -o public/cards/major-06.jpg && echo "  06 Lovers ✓"
curl -L "$BASE/9/9b/RWS_Tarot_07_Chariot.jpg" -o public/cards/major-07.jpg && echo "  07 Chariot ✓"
curl -L "$BASE/f/f5/RWS_Tarot_08_Strength.jpg" -o public/cards/major-08.jpg && echo "  08 Strength ✓"
curl -L "$BASE/4/4d/RWS_Tarot_09_Hermit.jpg" -o public/cards/major-09.jpg && echo "  09 Hermit ✓"
curl -L "$BASE/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg" -o public/cards/major-10.jpg && echo "  10 Wheel of Fortune ✓"
curl -L "$BASE/e/e0/RWS_Tarot_11_Justice.jpg" -o public/cards/major-11.jpg && echo "  11 Justice ✓"
curl -L "$BASE/2/2b/RWS_Tarot_12_Hanged_Man.jpg" -o public/cards/major-12.jpg && echo "  12 Hanged Man ✓"
curl -L "$BASE/d/d3/RWS_Tarot_13_Death.jpg" -o public/cards/major-13.jpg && echo "  13 Death ✓"
curl -L "$BASE/f/f8/RWS_Tarot_14_Temperance.jpg" -o public/cards/major-14.jpg && echo "  14 Temperance ✓"
curl -L "$BASE/5/55/RWS_Tarot_15_Devil.jpg" -o public/cards/major-15.jpg && echo "  15 Devil ✓"
curl -L "$BASE/5/53/RWS_Tarot_16_Tower.jpg" -o public/cards/major-16.jpg && echo "  16 Tower ✓"
curl -L "$BASE/d/db/RWS_Tarot_17_Star.jpg" -o public/cards/major-17.jpg && echo "  17 Star ✓"
curl -L "$BASE/7/7f/RWS_Tarot_18_Moon.jpg" -o public/cards/major-18.jpg && echo "  18 Moon ✓"
curl -L "$BASE/1/17/RWS_Tarot_19_Sun.jpg" -o public/cards/major-19.jpg && echo "  19 Sun ✓"
curl -L "$BASE/7/7d/RWS_Tarot_20_Judgement.jpg" -o public/cards/major-20.jpg && echo "  20 Judgement ✓"
curl -L "$BASE/f/ff/RWS_Tarot_21_World.jpg" -o public/cards/major-21.jpg && echo "  21 World ✓"

echo ""
echo "Downloading Wands..."
curl -L "$BASE/1/11/Wands01.jpg" -o public/cards/wands-01.jpg && echo "  Ace of Wands ✓"
curl -L "$BASE/0/0f/RWS_Tarot_Wands_02.jpg" -o public/cards/wands-02.jpg && echo "  Two of Wands ✓"
curl -L "$BASE/f/ff/RWS_Tarot_Wands_03.jpg" -o public/cards/wands-03.jpg && echo "  Three of Wands ✓"
curl -L "$BASE/a/a4/RWS_Tarot_Wands_04.jpg" -o public/cards/wands-04.jpg && echo "  Four of Wands ✓"
curl -L "$BASE/9/9d/RWS_Tarot_Wands_05.jpg" -o public/cards/wands-05.jpg && echo "  Five of Wands ✓"
curl -L "$BASE/3/3b/RWS_Tarot_Wands_06.jpg" -o public/cards/wands-06.jpg && echo "  Six of Wands ✓"
curl -L "$BASE/e/e4/RWS_Tarot_Wands_07.jpg" -o public/cards/wands-07.jpg && echo "  Seven of Wands ✓"
curl -L "$BASE/6/6b/RWS_Tarot_Wands_08.jpg" -o public/cards/wands-08.jpg && echo "  Eight of Wands ✓"
curl -L "$BASE/4/4d/RWS_Tarot_Wands_09.jpg" -o public/cards/wands-09.jpg && echo "  Nine of Wands ✓"
curl -L "$BASE/0/0b/RWS_Tarot_Wands_10.jpg" -o public/cards/wands-10.jpg && echo "  Ten of Wands ✓"
curl -L "$BASE/6/6a/Wands11.jpg" -o public/cards/wands-11.jpg && echo "  Page of Wands ✓"
curl -L "$BASE/1/16/Wands12.jpg" -o public/cards/wands-12.jpg && echo "  Knight of Wands ✓"
curl -L "$BASE/0/0d/Wands13.jpg" -o public/cards/wands-13.jpg && echo "  Queen of Wands ✓"
curl -L "$BASE/c/ce/Wands14.jpg" -o public/cards/wands-14.jpg && echo "  King of Wands ✓"

echo ""
echo "Downloading Cups..."
curl -L "$BASE/3/36/Cups01.jpg" -o public/cards/cups-01.jpg && echo "  Ace of Cups ✓"
curl -L "$BASE/f/f8/RWS_Tarot_Cups_02.jpg" -o public/cards/cups-02.jpg && echo "  Two of Cups ✓"
curl -L "$BASE/7/7a/RWS_Tarot_Cups_03.jpg" -o public/cards/cups-03.jpg && echo "  Three of Cups ✓"
curl -L "$BASE/3/35/RWS_Tarot_Cups_04.jpg" -o public/cards/cups-04.jpg && echo "  Four of Cups ✓"
curl -L "$BASE/d/d7/RWS_Tarot_Cups_05.jpg" -o public/cards/cups-05.jpg && echo "  Five of Cups ✓"
curl -L "$BASE/1/17/RWS_Tarot_Cups_06.jpg" -o public/cards/cups-06.jpg && echo "  Six of Cups ✓"
curl -L "$BASE/a/ae/RWS_Tarot_Cups_07.jpg" -o public/cards/cups-07.jpg && echo "  Seven of Cups ✓"
curl -L "$BASE/6/60/RWS_Tarot_Cups_08.jpg" -o public/cards/cups-08.jpg && echo "  Eight of Cups ✓"
curl -L "$BASE/2/24/RWS_Tarot_Cups_09.jpg" -o public/cards/cups-09.jpg && echo "  Nine of Cups ✓"
curl -L "$BASE/8/84/RWS_Tarot_Cups_10.jpg" -o public/cards/cups-10.jpg && echo "  Ten of Cups ✓"
curl -L "$BASE/a/ad/Cups11.jpg" -o public/cards/cups-11.jpg && echo "  Page of Cups ✓"
curl -L "$BASE/f/fa/Cups12.jpg" -o public/cards/cups-12.jpg && echo "  Knight of Cups ✓"
curl -L "$BASE/6/62/Cups13.jpg" -o public/cards/cups-13.jpg && echo "  Queen of Cups ✓"
curl -L "$BASE/0/04/Cups14.jpg" -o public/cards/cups-14.jpg && echo "  King of Cups ✓"

echo ""
echo "Downloading Swords..."
curl -L "$BASE/1/1a/Swords01.jpg" -o public/cards/swords-01.jpg && echo "  Ace of Swords ✓"
curl -L "$BASE/9/9e/RWS_Tarot_Swords_02.jpg" -o public/cards/swords-02.jpg && echo "  Two of Swords ✓"
curl -L "$BASE/0/02/RWS_Tarot_Swords_03.jpg" -o public/cards/swords-03.jpg && echo "  Three of Swords ✓"
curl -L "$BASE/b/bf/RWS_Tarot_Swords_04.jpg" -o public/cards/swords-04.jpg && echo "  Four of Swords ✓"
curl -L "$BASE/2/23/RWS_Tarot_Swords_05.jpg" -o public/cards/swords-05.jpg && echo "  Five of Swords ✓"
curl -L "$BASE/2/29/RWS_Tarot_Swords_06.jpg" -o public/cards/swords-06.jpg && echo "  Six of Swords ✓"
curl -L "$BASE/3/34/RWS_Tarot_Swords_07.jpg" -o public/cards/swords-07.jpg && echo "  Seven of Swords ✓"
curl -L "$BASE/a/a7/RWS_Tarot_Swords_08.jpg" -o public/cards/swords-08.jpg && echo "  Eight of Swords ✓"
curl -L "$BASE/2/2f/RWS_Tarot_Swords_09.jpg" -o public/cards/swords-09.jpg && echo "  Nine of Swords ✓"
curl -L "$BASE/d/d4/RWS_Tarot_Swords_10.jpg" -o public/cards/swords-10.jpg && echo "  Ten of Swords ✓"
curl -L "$BASE/e/e1/Swords11.jpg" -o public/cards/swords-11.jpg && echo "  Page of Swords ✓"
curl -L "$BASE/b/b0/Swords12.jpg" -o public/cards/swords-12.jpg && echo "  Knight of Swords ✓"
curl -L "$BASE/d/d4/Swords13.jpg" -o public/cards/swords-13.jpg && echo "  Queen of Swords ✓"
curl -L "$BASE/3/33/Swords14.jpg" -o public/cards/swords-14.jpg && echo "  King of Swords ✓"

echo ""
echo "Downloading Pentacles..."
curl -L "$BASE/f/fd/Pents01.jpg" -o public/cards/pentacles-01.jpg && echo "  Ace of Pentacles ✓"
curl -L "$BASE/9/9f/RWS_Tarot_Pentacles_02.jpg" -o public/cards/pentacles-02.jpg && echo "  Two of Pentacles ✓"
curl -L "$BASE/4/42/RWS_Tarot_Pentacles_03.jpg" -o public/cards/pentacles-03.jpg && echo "  Three of Pentacles ✓"
curl -L "$BASE/3/35/RWS_Tarot_Pentacles_04.jpg" -o public/cards/pentacles-04.jpg && echo "  Four of Pentacles ✓"
curl -L "$BASE/9/96/RWS_Tarot_Pentacles_05.jpg" -o public/cards/pentacles-05.jpg && echo "  Five of Pentacles ✓"
curl -L "$BASE/a/a6/RWS_Tarot_Pentacles_06.jpg" -o public/cards/pentacles-06.jpg && echo "  Six of Pentacles ✓"
curl -L "$BASE/6/6a/RWS_Tarot_Pentacles_07.jpg" -o public/cards/pentacles-07.jpg && echo "  Seven of Pentacles ✓"
curl -L "$BASE/4/49/RWS_Tarot_Pentacles_08.jpg" -o public/cards/pentacles-08.jpg && echo "  Eight of Pentacles ✓"
curl -L "$BASE/f/f0/RWS_Tarot_Pentacles_09.jpg" -o public/cards/pentacles-09.jpg && echo "  Nine of Pentacles ✓"
curl -L "$BASE/4/42/RWS_Tarot_Pentacles_10.jpg" -o public/cards/pentacles-10.jpg && echo "  Ten of Pentacles ✓"
curl -L "$BASE/e/ec/Pents11.jpg" -o public/cards/pentacles-11.jpg && echo "  Page of Pentacles ✓"
curl -L "$BASE/d/d5/Pents12.jpg" -o public/cards/pentacles-12.jpg && echo "  Knight of Pentacles ✓"
curl -L "$BASE/8/88/Pents13.jpg" -o public/cards/pentacles-13.jpg && echo "  Queen of Pentacles ✓"
curl -L "$BASE/1/1c/Pents14.jpg" -o public/cards/pentacles-14.jpg && echo "  King of Pentacles ✓"

echo ""
echo "✓ Done! Checking download..."
COUNT=$(ls public/cards/*.jpg 2>/dev/null | wc -l)
echo "$COUNT card images in public/cards/"
